# syntax=docker/dockerfile:1

ARG RUBY_VERSION=4.0.7
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      libpq-dev \
      libvips \
      libyaml-dev \
      pkg-config \
      postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

ENTRYPOINT ["./bin/docker-entrypoint-dev"]

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
